language: node_js
node_js:
 - 13

services:
 - docker

# Pre-testing installs
install:
 - echo "nothing needs to be installed."

# Scripts to be run such as tests
before_script:
 - echo "no tests. Yes there will be tests."

script:
 - docker --version # prints the version for logging here
 - docker build -t reverseproxy ./udagram-reverseproxy
 - docker build -t udagram-api-feed ./udagram-api-feed
 - docker build -t udagram-api-user ./udagram-api-user
 - docker build -t udagram-frontend ./udagram-frontend

# Tagging
 - docker tag reverseproxy itsmiguel/reverseproxy:v0.1
 - docker tag udagram-api-feed itsmiguel/udagram-api-feed:v0.1
 - docker tag udagram-api-user itsmiguel/udagram-api-user:v0.1
 - docker tag udagram-frontend itsmiguel/udagram-frontend:local

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you
after_success:
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker push itsmiguel/reverseproxy:v0.1
 - docker push itsmiguel/udagram-api-feed:v0.1
 - docker push itsmiguel/udagram-api-user:v0.1
 - docker push itsmiguel/udagram-frontend:local