apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-feed
  labels:
    app: api-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-feed
  template:
    metadata:
      labels:
        app: api-feed
    spec:
      containers:
        - name: api-feed
          image: itsmiguel/udagram-api-feed:v0.1
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "500m"
            requests:
              cpu: "200m"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: udagram-env
            - secretRef:
                name: udagramdb-env
          volumeMounts:
            - mountPath: "/root/.aws/"
              name: mysecret
      volumes:
        - name: mysecret
          configMap:
            name: mysecret