apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user
  labels:
    app: api-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-user
  template:
    metadata:
      labels:
        app: api-user
    spec:
      containers:
      - name: api-user
        image: itsmiguel/udagram-api-user:v0.1
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "500m"
          requests:
            cpu: "200m"
        ports:
        - containerPort: 80
        envFrom:
            - configMapRef:
                name: udagram-env
            - secretRef:
                name: udagramdb-env
