apiVersion: v1
kind: ConfigMap
metadata:
  name: mysecret
data:
  credentials: |
    [default]
    aws_access_key_id = AKIARDS76UHXU6SJOBVB
    aws_secret_access_key = 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
  